### ISSUE TITLE
Update README.md to include Script Parameter note for removeTempAdmin.py

### ISSUE THREAD

**Issue by dan-snelson** [kc9wwh/MakeMeAdminPy#6]
The "removeTempAdmin.py" includes a Script Parameter at line 75; please update the README.md to add a Parameter Label.

**Comment by kc9wwh** [comment]
I think you should get a prize for finding that @dan-snelson! After 2+ years of being posted you are the first to point out that I didn't include that in the readme. :)

I'll get that updated and we'll have to work out something at JNUC!

**Comment by kc9wwh** [comment]
There we go 😄 
Let me know if that update doesn't work.
